add main_svc
Sheikhovskiy/java-explore-with-me pull request #2
Opened 2024-12-03 18:39 UTC by Sheikhovskiy

2024-12-04 04:08 UTC, sergeymamonov requested changes

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/compilation/dto/CompilationDto.java
> +@Setter
dto это неизменяемый объект, у него не может быть сеттера. Плюс можете посмотреть, как сделать класс неизменяемым.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/category/service/CategoryServiceImpl.java
> +    private static final String CATEGORY_ALREADY_EXIST = "Ошибка при работе с категориями: Категория {} " +
Чтобы потом значение подставилось нужно использовать %s. Проверьте в дебаге или тесте везде выводимый тест ошибки.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        Long categoryId = adminEventParam.getCategory();
Обращайте внимание на подсказки среды разработки. В данном случае она подсказывала, что переменная нигде не используется.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        System.out.println(eventToModify.getRequestModeration());
Похоже на какую-то отладочную информацию, а не продакшен код. Проверьте поиском по всему проекту, нет ли в других местах.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +                throw new RuntimeException(e);
Не нужно кидать RuntimeException. Вы отлавливаете специфическое исключение JsonProcessingException и вместо него кидаете общение исключение RuntimeException. То есть усложняете работу себе и остальным при отладке такого кода. Разработчик не кидает RuntimeException. Если нужно кинуть ошибку разработчик кидает свою или из какой-то библиотеки.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +                    field.set(eventToModify, valueExisting);
Не нужно в продакшен коде использовать рефлексию. Нужно найти способы использовать стандартную библиотеку(у), но не рефлексию.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        Location location = locationRepository.save(eventToModify.getLocation());
Проверьте весь код проекта на неиспользуемые переменные.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Литерал лучше вынести в константу, чтобы записать его один раз и не несколько по всему проекту.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/EventMapper.java
> +//        event.setCategory(updateEventAdminRequest.getCategory());
Не оставляйте в проекте закомментированный код. Проверьте по всему проекту.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/EventSortState.java
> +public enum EventSortState {
Это перечисление где-то используется?

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/java/ewm/user/service/UserServiceImpl.java
> +                throw new RuntimeException(e);
Поищите по всему проекту, где кидается RuntimeException. И нужно отказаться от этого. Разработчик не кидает RuntimeException.

2024-12-04 04:08 UTC, sergeymamonov commented on main-service/src/main/resources/schema.sql
> +    email VARCHAR(254),
Сейчас во всех таблицах все поля могут быть null. Такое может быть? Например, юзер без почты? Если да, то код приложения должен быть к этому готов.

2024-12-04 14:29 UTC, Sheikhovskiy commented on main-service/src/main/java/ewm/compilation/dto/CompilationDto.java
> +@Setter
CompilationDto выполняют функцию, возвращаемого объекта. Сущность Complation преобразуется в CompilationDto

2024-12-05 04:21 UTC, sergeymamonov commented on main-service/src/main/java/ewm/compilation/dto/CompilationDto.java
> +@Setter
Это происходит один раз? Для этого подойдет конструктор, билдер.

2024-12-05 04:24 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        System.out.println(eventToModify.getRequestModeration());
Поиском по проекту Command+Shift+F поищите System.out.println, еще много где осталось.

2024-12-05 04:25 UTC, sergeymamonov commented on main-service/src/main/java/ewm/category/service/CategoryServiceImpl.java
> +    private static final String CATEGORY_ALREADY_EXIST = "Ошибка при работе с категориями: Категория {} " +
Поиском по проекту поищите {} в String.format. Еще остались места.

2024-12-05 04:26 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/EventMapper.java
> +//        event.setCategory(updateEventAdminRequest.getCategory());
Поиском по проекту поищите //. Еще остались места.

2024-12-05 04:27 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +                throw new RuntimeException(e);
Поиск по проекту throw new RuntimeException. Не все исправлено.

2024-12-05 04:28 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +                    field.set(eventToModify, valueExisting);
Поиск по проекту reflect. Если осталось место.

2024-12-05 04:28 UTC, sergeymamonov commented on main-service/src/main/java/ewm/event/service/EventServiceImpl.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Выполните поиск по проекту по yyyy-MM-dd HH:mm:ss

2024-12-05 04:29 UTC, sergeymamonov approved these changes

2024-12-05 10:13 UTC, Sheikhovskiy commented on main-service/src/main/java/ewm/compilation/dto/CompilationDto.java
> +@Setter
Используется почти для всех ответов в контроллерах, связанных с пакетом Compilation

2024-12-05 10:23 UTC, merged